name: socket
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  udp: ^5.0.3
  shelf_web_socket: ^1.0.3
  dio: ^4.0.6
  http: ^0.13.5
  web_socket_channel: ^2.3.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
